%Doctor.Config{
  ignore_modules: [
    ~r/^Jidoka\.Agent\.Dsl(?:\.|$)/,
    ~r/^Jidoka\.Agent\.Spec(?:\.|$)/,
    ~r/^Jidoka\.Agent\.ToolSources$/,
    ~r/^Jidoka\.Browser\.(Runtime|Tools)(?:\.|$)/,
    ~r/^Jidoka\.Effect(?:\.|$)/,
    ~r/^Jidoka\.Eval\.(Case|Run)$/,
    ~r/^Jidoka\.Extension\.Patch$/,
    ~r/^Jidoka\.Handoff\.OwnerStore(?:\.|$)/,
    ~r/^Jidoka\.Harness\.(Replay|Session|Store)(?:\.|$)/,
    ~r/^Jidoka\.Import(?:\.|$)/,
    ~r/^Jidoka\.Inspection\.Preflight$/,
    ~r/^Jidoka\.Memory\.(Compaction|Entry|RecallRequest|RecallResult|Runtime|Store|WriteRequest|WriteResult)(?:\.|$)/,
    ~r/^Jidoka\.Operation(?:\.|$)/,
    ~r/^Jidoka\.Projection$/,
    ~r/^Jidoka\.Review\.(Interrupt|Request|Response)$/,
    ~r/^Jidoka\.Runtime(?:\.|$)/,
    ~r/^Jidoka\.Trace\.(Policy|Sink)(?:\.|$)/,
    ~r/^Jidoka\.Turn(?:\.|$)/,
    ~r/^Jidoka\.Workflow\.(Codegen|Definition|Dsl|ParametersSchema|Runtime|SparkDsl)(?:\.|$)/
  ],
  ignore_paths: [],
  min_module_doc_coverage: 40,
  min_module_spec_coverage: 0,
  min_overall_doc_coverage: 50,
  min_overall_moduledoc_coverage: 100,
  min_overall_spec_coverage: 80,
  exception_moduledoc_required: true,
  raise: false,
  reporter: Doctor.Reporters.Summary,
  struct_type_spec_required: true,
  umbrella: false
}
