# Used by "mix format"
[
  locals_without_parens: [
    action: 1,
    after_turn: 1,
    agent: 2,
    agent: 3,
    ash_resource: 1,
    before_turn: 1,
    capture: 1,
    compaction: 1,
    conversation: 1,
    controls: 1,
    cron: 1,
    description: 1,
    handoff: 1,
    handoff: 2,
    id: 1,
    inject: 1,
    input: 1,
    instructions: 1,
    keep_last: 1,
    load_path: 1,
    max_messages: 1,
    max_summary_chars: 1,
    mcp_tools: 1,
    memory: 1,
    mode: 1,
    model: 1,
    namespace: 1,
    on_interrupt: 1,
    on_validation_error: 1,
    operation: 1,
    overlap: 1,
    plugin: 1,
    prompt: 1,
    repair: 1,
    retrieve: 1,
    result: 1,
    schedule: 1,
    schema: 1,
    shared_namespace: 1,
    skill: 1,
    steps: 1,
    subagent: 1,
    subagent: 2,
    function: 2,
    function: 3,
    tool: 1,
    tool: 2,
    tool: 3,
    tools: 1,
    timezone: 1,
    value: 1,
    workflow: 1,
    output: 1
  ],
  inputs: [
    "{mix,.formatter}.exs",
    "{config,examples,lib,test}/**/*.{ex,exs}",
    "livebook/**/*.livemd"
  ],
  line_length: 120
]
