# Used by "mix format"
[
  locals_without_parens: [
    action: 1,
    agent: 2,
    agent: 3,
    ash_resource: 1,
    controls: 1,
    description: 1,
    context: 1,
    handoff: 1,
    handoff: 2,
    id: 1,
    input: 1,
    instructions: 1,
    load_path: 1,
    mcp_tools: 1,
    model: 1,
    on_validation_error: 1,
    operation: 1,
    operation: 2,
    plugin: 1,
    repair: 1,
    result: 1,
    skill: 1,
    steps: 1,
    subagent: 1,
    subagent: 2,
    function: 2,
    function: 3,
    tool: 1,
    tool: 2,
    tool: 3,
    tools: 1,
    value: 1,
    web: 1,
    workflow: 1,
    workflow: 2,
    output: 1
  ],
  inputs: [
    "{mix,.formatter}.exs",
    "{config,examples,lib,test}/**/*.{ex,exs}",
    "livebook/**/*.livemd"
  ],
  line_length: 120
]
