# Used by "mix format"
[
  plugins: [Spark.Formatter],
  locals_without_parens: [
    action: 1,
    agent: 1,
    agent: 2,
    ash_resource: 1,
    ash_resource: 2,
    browser: 1,
    browser: 2,
    catalog: 1,
    catalog: 2,
    controls: 1,
    context: 1,
    generation: 1,
    handoff: 1,
    handoff: 2,
    input: 1,
    instructions: 1,
    load_path: 1,
    max_turns: 1,
    memory: 1,
    mcp_tools: 1,
    model: 1,
    operation: 1,
    operation: 2,
    output: 1,
    result: 1,
    skill: 1,
    subagent: 1,
    subagent: 2,
    timeout: 1,
    tools: 1,
    workflow: 1,
    workflow: 2
  ],
  inputs: ["{mix,.formatter,.credo,.doctor}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  line_length: 120
]
